package servlet.shoppingCart;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class ShoppingCart extends HttpServlet {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
			resp.setContentType("text/html;charset=utf-8");
		    resp.setCharacterEncoding("UTF-8");
		    PrintWriter out = resp.getWriter();
		    out.println("<html>");
		    out.println("	<head>");
		    out.println("		<title>达内电子商务门户</title>");
		    out.println("		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">");
		    out.println("		<meta name=\"description\" content=\"达内电子商务门户\">");
		    out.println("		<link href=\"css/tarena.css\" rel=stylesheet>");
		    out.println("	</head>");
		    out.println("	<body topmargin=\"0\" leftmargin=\"0\" rightmargin=\"0\" bottommargin=\"0\">");
		    out.println("<!-- Header Start -->");
		    out.println("		<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"table2\">");
		    out.println("			<tr>");
		    out.println("				<td align=\"left\" width=\"7%\" background=\"images/top_bg.gif\"><img src=\"images/logo.gif\" width=\"286\" height=\"58\"></td>");
		    out.println("				<td width=\"62%\" background=\"images/top_bg.gif\">　</td>");
		    out.println("				<td width=\"31%\" background=\"images/top_bg.gif\" align=\"right\"><img src=\"images/top_r.gif\" width=\"352\" height=\"58\" border=\"0\"></td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("		<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
		    out.println("			<tr>");
		    out.println("				<td background=\"images/dh_bg.gif\" align=\"left\" height=\"12\">");
		    out.println("					<table width=\"100\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
		    out.println("						<tr>");
		    out.println("							<td width=\"5%\"></td>");
		    out.println("							");
		    out.println("          <td width=\"10%\"><a href=\"product2\"><img name=\"Image1\" border=\"0\" src=\"images/index.gif\" width=\"90\" height=\"36\"></a></td>");
		    out.println("							");
		    out.println("          <td width=\"10%\"><a href=\"user2\"><img name=\"Image2\" border=\"0\" src=\"images/reg.gif\" width=\"92\" height=\"36\"></a></td>");
		    out.println("							");
		    out.println("          <td width=\"10%\"><a href=\"shop2\"><img name=\"Image4\" border=\"0\" src=\"images/cart.gif\" width=\"92\" height=\"36\"></a></td>");
		    out.println("							");
		    out.println("          <td width=\"10%\"><a href=\"order2\"><img name=\"Image5\" border=\"0\" src=\"images/order.gif\" width=\"92\" height=\"36\"></a></td>");
		    out.println("							");
		    out.println("          <td width=\"10%\"><a href=\"product2\"><img name=\"Image6\" border=\"0\" src=\"images/exit.gif\" width=\"92\" height=\"36\"></a></td>");
		    out.println("						</tr>");
		    out.println("					</table>");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("		<table cellspacing=\"1\" cellpadding=\"3\" align=\"center\" border=\"0\" width=\"98%\">");
		    out.println("			<tr>");
		    out.println("				<td width=\"65%\"><br>");
		    out.println("					>> 欢迎访问 <b>达内电子商务门户</b>");
		    out.println("				</td>");
		    out.println("				<td width=\"35%\" align=\"right\">");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("<!-- Header End -->");
		    out.println("<!-- Body Start -->");
		    out.println("		<table cellspacing=\"1\" cellpadding=\"3\" align=\"center\" class=\"tableBorder2\">");
		    out.println("			<tr>");
		    out.println("				<td height=\"25\" valign=\"middle\">");
		    out.println("					<img src=\"images/Forum_nav.gif\" align=\"absmiddle\">");
		    out.println("					<a href=index.jsp>达内电子商务门户</a> →<img border=\"0\" src=\"images/dog.gif\" width=\"19\" height=\"18\"><b>购物清单</b>");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("		<br>");
		    out.println("		<table cellpadding=\"3\" cellspacing=\"1\" align=\"center\" class=\"tableborder1\">");
		    out.println("			<tr>");
		    out.println("				<td valign=\"middle\" align=\"center\" height=\"25\" background=\"images/bg2.gif\" width=\"8%\">");
		    out.println("					<font color=\"#ffffff\">");
		    out.println("						<b>序号</b>");
		    out.println("					</font>");
		    out.println("				</td>");
		    out.println("				<td valign=\"middle\" align=\"center\" height=\"25\" background=\"images/bg2.gif\" width=\"44%\">");
		    out.println("					<font color=\"#ffffff\">");
		    out.println("						<b>产品名称</b>");
		    out.println("					</font>");
		    out.println("				</td>");
		    out.println("				<td valign=\"middle\" align=\"center\" height=\"25\" background=\"images/bg2.gif\" width=\"8%\">");
		    out.println("					<font color=\"#ffffff\">");
		    out.println("						<b>价格</b>");
		    out.println("					</font>");
		    out.println("				</td>");
		    out.println("				<td valign=\"middle\" align=\"center\" height=\"25\" background=\"images/bg2.gif\" width=\"8%\">");
		    out.println("					<font color=\"#ffffff\">");
		    out.println("						<b>数量</b>");
		    out.println("					</font>");
		    out.println("				</td>");
		    out.println("				<td valign=\"middle\" align=\"center\" height=\"25\" background=\"images/bg2.gif\" width=\"8%\">");
		    out.println("					<font color=\"#ffffff\">");
		    out.println("						<b>合计</b>");
		    out.println("					</font>");
		    out.println("				</td>");
		    out.println("				<td valign=\"middle\" align=\"center\" height=\"25\" background=\"images/bg2.gif\" width=\"24%\">");
		    out.println("					<font color=\"#ffffff\">");
		    out.println("						<b>操作</b>");
		    out.println("					</font>");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("			<tr>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					1");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"44%\">");
		    out.println("					精通Hibernate：Java对象持久化技术详解");
		    out.println("				</td>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					59.0");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					<input type=\"text\" value=\"1\" size=\"2\">");
		    out.println("				</td>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					<b>￥59.0</b>");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"24%\">");
		    out.println("					<input type=\"button\" value=\"取消\" size=\"1\">");
		    out.println("					<input type=\"button\" value=\"保存修改\" size=\"2\">");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("			<tr>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					2");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"44%\">");
		    out.println("					Effictive Java中文版");
		    out.println("				</td>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					39.0");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					<input type=\"text\" value=\"2\" size=\"2\">");
		    out.println("				</td>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					<b>￥78.0</b>");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"24%\">");
		    out.println("					<input type=\"button\" value=\"取消\" size=\"1\">");
		    out.println("					<input type=\"button\" value=\"保存修改\" size=\"2\">");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("			<tr>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"8%\" colspan=\"4\">");
		    out.println("					");
		    out.println("				</td>");
		    out.println("				");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\">");
		    out.println("					<font color=\"red\"><b>￥137.0</b></font>");
		    out.println("				</td>");
		    out.println("				<td class=tablebody1 valign=\"middle\" align=\"center\" width=\"24%\">");
		    out.println("					");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("			<tr>");
		    out.println("				<td class=tablebody2 valign=\"middle\" align=\"center\" width=\"8%\" colspan=\"6\">");
		    out.println("				<form>");
		    out.println("					<input type=\"button\" value=\"提交订单\" size=\"1\" onclick=\"javascript:window.location='shop1';\">");
		    out.println("					<input type=\"button\" value=\"继续购物\" size=\"2\" onclick=\"javascript:window.location='product2';\">");
		    out.println("					<input type=\"button\" value=\"清空购物车\" size=\"2\" onclick=\"javascript:window.location='product2';\">");
		    out.println("				</form>");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("		<br>");
		    out.println("		");
		    out.println("		");
		    out.println("		");
		    out.println("		");
		    out.println("<!-- Footer Start -->");
		    out.println("		<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" height=\"28\">");
		    out.println("			<tr>");
		    out.println("				<td height=\"17\" background=\"images/bot_bg.gif\">");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("		<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
		    out.println("			<tr>");
		    out.println("				<td bgcolor=\"#f1f1f6\" height=\"53\" valign=\"center\">");
		    out.println("					<p align=\"center\">");
		    out.println("						Copyright &copy;2004 - 2005 <a href=\"http://www.tarena.com.cn\"><b>Tarena</b><font color=\"red\">.com.cn</font></a>");
		    out.println("					</p>");
		    out.println("				</td>");
		    out.println("			</tr>");
		    out.println("		</table>");
		    out.println("<!-- Footer End -->");
		    out.println("	</body>");
		    out.println("</html>");
	}
	
	private void toError(HttpServletResponse resp, String message) throws IOException {
		resp.setContentType("text/html;charset=UTF-8");
		PrintWriter out = resp.getWriter();
		out.println("<html>    "); 
		
		 out.println("<head>    "); 
		 out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />    "); 
		 out.println("<title>网站正在建设中，请稍候再试</title>    "); 
		 out.println("<style>    "); 
		 out.println("body{font-family:Helvetica,Arial,sans-serif;margin:0;background-color:#CCC;background:-webkit-linear-gradient(#CCC,#AAA);background-attachment:fixed;}#cell{padding:40px;}#box{background-color:white;color:black;font-size:10pt;line-height:18px;margin:auto;max-width:800px;border-radius:5px;-webkit-box-shadow:2px 5px 12px#555;padding:20px;}    "); 
		 out.println("ul{margin:0;padding-bottom:0;}    "); 
		 out.println("li{padding-top:2px;}    "); 
		 out.println("h1{font-size:18pt;line-height:30px;margin:0;}    "); 
		 out.println(".right{color:#00FF00;text-align: right;}    "); 
		 out.println("a{color:#B5B5B5;}    "); 
		 out.println("</style>    "); 
		 out.println("</head>    "); 
		 out.println("<body id=\"t\">    "); 
		 out.println("<div id=\"cell\">    "); 
		 out.println("<div id=\"box\">    "); 
		 out.println("<body bgcolor=#rrggbb>"); 
		 out.println("<font bgcolor=#00FF00></font>");
		 out.println("<font face=\"隶书\"></font>");
		 out.println("<h1>有点小错误啊，请稍候再试好不好哇.....</h1>    "); 
		 out.println("<p>    "); 
		 out.println("<ul>    "); 
		 out.println("<h3>");
		 out.println("<li>粗枝大叶没有设置默认页</li>    "); 
		 out.println("<br>");
		 out.println("<li>贵人多忘事没有上传程序</li>    "); 
		 out.println("<br>");
		 out.println("<li>不干了网站荒废已经长草</li>    "); 
		 out.println("<br>");
		 out.println("<li>怒火攻心把网站咔嚓掉了</li>    "); 
		 out.println("<br>");
		 out.println("<li>有个二货把域名CNAME到这里</li>    "); 
		 out.println("<br>");
		 out.println("<br>");
		 out.println("<li>要不去百度玩玩???</li>    "); 
		 out.println("</h3>");
		 out.println("</ul>    "); 
		 out.println("</p>    "); 
		 out.println("<body link=#rrggbb> ");
		 out.println("<p class=\"right\">&copy; 2015 @<a href=\"http://www.baidu.com\">百度一下  你就知道:</a></p>    "); 
		 out.println("</div>    "); 
		 out.println("</div>    "); 
		 out.println("</body>    "); 
		 out.println("</html>    ");
		
		out.close();
	}
	
	public void doPost(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
			
		}

}
